# ATSAMC21E17A: 32 pins, PORTA only, 128 KB flash, 16 KB RAM, a 4 KB RWW section used as EEPROM, SERCOM0-3, CAN0.
set(TARGET_MPU ATSAMC21E17A)
set(TARGET_FLASH_SIZE 131072)
set(TARGET_RAM_SIZE 16384)
set(TARGET_EEPROM_SIZE 4096)

set(LINKER_FILE ${CMAKE_CURRENT_LIST_DIR}/../../linker/chip.ld)
set(CHIP_SVD_FILE ${CMAKE_CURRENT_LIST_DIR}/../../chip.svd)
